<?xml version="1.0"?>
<package format="3">
  <name>pac_planning</name><version>0.1.0</version>
  <description>AHEAD mixed palletizing module</description>
  <maintainer email="maintainers@example.invalid">AHEAD team</maintainer>
  <license>LicenseRef-All-Rights-Reserved</license>
  <exec_depend>pac_common</exec_depend>
  <exec_depend>pac_candidates</exec_depend>
  <exec_depend>pac_planning_interfaces</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
